- title: Rough Seas
  subtitle: Katami Coast/Shelikof Straight
  images:
    - /assets/images/adventures/rough_seas/8_000234.jpg
    - /assets/images/adventures/rough_seas/9_000412.jpg
    - /assets/images/adventures/rough_seas/10_001360.jpg
    - /assets/images/adventures/rough_seas/11_001192.jpg
    - /assets/images/adventures/rough_seas/12_001926.jpg
    - /assets/images/adventures/rough_seas/13_001345.jpg
    - /assets/images/adventures/rough_seas/14_001256.jpg
  content: |-
    The prospect of photographing grizzlies drew Steve out in a small boat into the waters of
    Southcentral Alaska where a sudden fall storm made for one of the most harrowing tales in
    his quest for Alaskan wildlife.

    Setting out in a 26 foot sail boat, Steve and a colleague followed the Katmai Coast,
    capturing dramatic images of bears along the steep, rugged shores.

    Knowing fall was approaching when the seas can be particularly treacherous, they
    watched the weather and thought the 20 hour short-cut across the Shelikof Straight seemed
    like a safe bet.

    Across the sound, the engine died. Then the weather changed. Winds picked up – in the
    opposite direction they wanted to go. 40 knot winds and 20 foot waves buffeted the small
    boat. Bilge pumps struggled to keep up, hour after hour.

    In the pitch black of night, they retreated for St. Augustine Island, a volcanic island
    jutting out of the Katchemak Bay, in search of safety on the leeward side. Just before
    losing contact with the Coast Guard, they prepared their survival suits, fearing the worst.
    Finally reaching the island, they awoke in daylight anchored between two huge boulders on
    either side of the boat, which would have sunk the boat given less luck.

    A Coast Guard helicopter flew by to see if they were still alive. Indeed they were.

- title: Polar Bear Play
  subtitle: Alaskan Arctic Coast
  images:
    - /assets/images/adventures/polar_bear_play/1_001830.jpg
    - /assets/images/adventures/polar_bear_play/2_001833.jpg
    - /assets/images/adventures/polar_bear_play/3_001832.jpg
    - /assets/images/adventures/polar_bear_play/4_001837.jpg
    - /assets/images/adventures/polar_bear_play/5_000123.jpg
    - /assets/images/adventures/polar_bear_play/6_001899.jpg
    - /assets/images/adventures/polar_bear_play/7_001840.jpg
  content: |-
    To photograph polar bears on the Arctic coast, Steve must get close - but not too close -
    to the ferocious yet sometimes playful creatures.

    Hanging out on the Arctic coast, Steve spotted spring cubs with their mother, who eyed him
    warily. The cubs however, playing tag with each other like school children, would charge at
    Steve then run off.

    After a few days, the mother let her guard down. She left the cubs playing this game with
    Steve while she went off to feed on a whale carcass.

    One particularly curious bear tested Steve. The young adult bear would see how close it could
    get before Steve would retreat. Watching Steve’s response, the bear altered its tactics.
    Dropping to the snow, it rolled around playfully, pretending to ignore Steve. Feeling safe,
    Steve dropped to his belly, one eye glued to his camera. Slowly, the bear pushed itself
    toward Steve. Slyly, it did this until Steve realized the bear was a mere 15 feet way!

- title: Search for the Spirit Bear
  subtitle: Central British Columbia Coast
  images:
    - /assets/images/adventures/search_for_the_spirit_bear/1_001813.jpg
    - /assets/images/adventures/search_for_the_spirit_bear/2_001811.jpg
    - /assets/images/adventures/search_for_the_spirit_bear/3_001995.jpg
    - /assets/images/adventures/search_for_the_spirit_bear/4_004661.jpg
    - /assets/images/adventures/search_for_the_spirit_bear/5_002302.jpg
    - /assets/images/adventures/search_for_the_spirit_bear/6_001808.jpg
    - /assets/images/adventures/search_for_the_spirit_bear/7_001805.jpg
    - /assets/images/adventures/search_for_the_spirit_bear/8_004729.jpg
  content: >-
    Native Americans believed that when the glaciers of the ice age retreated in the north, the
    Creator left some bears white to remind man that ice gave life to the land.

    These white black bears are extremely rare, lacking a gene to give their coat its black color.
    Steve set out to the last area where a small population exists – near Princess Royal Island.
    After convincing a tour group to drop him off in the remote area, Steve set up his tent near a
    stream where bears feed only catching glimpses of the elusive spirit bear over five days. With
    time running out on his trip, Steve emerged one evening from his tent to see the spirit bear.
    Startled, it charged at him over a log, its hair up, ears back, snapping its jaws.

    Speaking to it calmly, Steve backed away from the bear and it eventually left. Believing he
    lost the opportunity to photograph a spirit bear, Steve built a blind and patiently waited.
    It paid off - the spirit bear eventually returned and felt more comfortable with him and his
    camera.
