carousel_images:
  - /assets/images/current_project/The_Last_Polar_BearCvr.jpg
  - /assets/images/current_project/1_000261.jpg
  - /assets/images/current_project/2_003879.jpg
  - /assets/images/current_project/3_005775.jpg
  - /assets/images/current_project/4_006506.jpg
  - /assets/images/current_project/5_006521.jpg
  - /assets/images/current_project/6_006087.jpg
  - /assets/images/current_project/7_006637.jpg
  - /assets/images/current_project/8_006112.jpg
  - /assets/images/current_project/9_001823.jpg
  - /assets/images/current_project/10_11747.jpg
  - /assets/images/current_project/11_12049.jpg
  - /assets/images/current_project/12_12499.jpg
  - /assets/images/current_project/13_13630.jpg
  - /assets/images/current_project/14_15224.jpg
  - /assets/images/current_project/15_15409.jpg
  - /assets/images/current_project/16_15294.jpg
content: |-
  ## The Last Polar Bear: Facing the Truth of a Warming World

  Braided River Books, February 28, 2008 235 color photos.

  192 pages, 10x12, Hardcover.

  ***The Last Polar Bear*** records and celebrates one of nature’s most majestic creatures - the polar bear  - and
  examines how global warming is affecting the fragile, complex Arctic environment.

  Polar bears use sea ice to move about, find mates and hunt for seals. As temperatures warm, the loss of the pack ice
  directly impacts their ability to survive. Scientists agree that Arctic ice is disappearing at an alarming rate. Last
  summer, sea ice levels plummeted to their lowest since satellite measurements began in 1979. And a new scientific
  study by the U.S. Geological Survey, released last fall, predicts that two-thirds of the world’s polar bears,
  including Alaska’s entire population, may disappear completely by 2050.

  For the past eight years, wildlife photographer Steven Kazlowski traveled to the remote Beaufort and Chukcki Seas,
  from Point Hope in western Alaska to Herschel Island in the Yukon to photograph these magnificent creatures and record
  the intricacies of this delicately balanced ecosystem.

  The book includes many such anecdotes of life among the bears, relayed by the photographer, Alaskan natives and
  Inupiaq elders. Essays written by conservationist Theodore Roosevelt IV, Natural Resources Defense Council President
  Frances Beinecke, cultural anthropologist Richard Nelson, environmental journalist Daniel Glick, and Alaskan residents
  and writers Nick Jans and Charles Wohlforth provide a more in-depth understanding of the scientific, political and
  social issues that surround climate change.

  ## Presentations

  A 10-city national author tour and an educational outreach campaign, held in collaboration with leading conservation
  organizations, is planned.  Dates and locations are to be determined.  Check back for the schedule.

  ## Museum Exhibit

  Burke Museum of Natural History and Culture, Seattle, WA

  June 28 – December 31, 2008

  *This is a national traveling exhibit that begins at the Burke. Check back for future venues.*
sponsors:
  - /assets/images/sponsors/or_logo.gif
  - /assets/images/sponsors/patagonia_logo.gif
  - /assets/images/sponsors/sww.jpg
  - /assets/images/sponsors/wiggys.jpg
get_involved:
  - name: Natural Resources Defense Council
    url: https://www.nrdc.org/wildlife/habitat/esa/alaska01.asp

  - name: Center for Biological Diversity
    url: https://www.biologicaldiversity.org/swcbd/SPECIES/polarbear/index.html

  - name: World Wildlife Fund
    url: https://worldwildlife.org/polarbears/
